Add docker compose
Cleopha/ifttt-like pull request #92
Opened 2022-03-02 08:07 UTC by Cleopha

# Description

- Docker compose that run all backend project

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [ ] I have tested this code
- [X] I have added sufficient documentation in the code

2022-03-02 08:10 UTC, 0xpanoramix approved these changes
LGTM !

2022-03-02 22:22 UTC, TomChv requested changes
:warning: You forget to rebase!

Looks good overall, small comments

2022-03-02 22:22 UTC, TomChv commented on .env.example
> +PRODUCER_ENDPOINT="127.0.0.1:19092" # I guess is useless
I agree, put it directly in compose

2022-03-02 22:22 UTC, TomChv commented on .env.example
> +BROKER_ADDRESS=http://localhost:19092 # I guess is useless
Same

2022-03-02 22:22 UTC, TomChv commented on .env.example
> +REDIS_PASS_IDEFIX=idefix_pass
Should be empty

2022-03-02 22:22 UTC, TomChv commented on docker-compose.yml
> +    # I have to delete the exposure of the ports if I have put in the same network ?
It depends if you want to expose it publicly or nope, I guess no but it's up to you

2022-03-02 22:22 UTC, TomChv commented on docker-compose.yml
> +    # I have to delete the exposure of the ports if I have put in the same network ?
It depends if you want to expose it publicly or nope, I guess no but it's up to you

2022-03-04 22:59 UTC, TomChv approved these changes
LGTM

2022-03-04 22:59 UTC, merged